return {
  {"Back-to-Back", "n.", "The action of performing two tetras,\nT-spin clears, or a mix of the two\none after the other"},
  {"Block", "n.", "A small square that occupies one of the\ncells of the matrix"},
  {"Brew", "n.", "A coffee obtained by the player"},
  {"Bite", "n.", "A pastry obtained by the player"},
  {"Cache", "n.", "The total amount of lines available for\nthe player to spend at the Hard Drop Café"},
  {"Cell", "n.", "A small square that resides within the\nmatrix"},
  {"Clear", "n., v.", "The action of completing at least one line\nof blocks on the matrix"},
  {"Double", "n.", "A two-line clear"},
  {"Hard Drop", "n., v.", "The action of dropping a tetromino\nimmediately onto the board, locking it\nfrom any further movement"},
  {"Hold", "n., v.", "The action of storing a tetromino\nfor later use, bringing out the\npreviously saved tetromino, or the\nnext tetromino if none were saved"},
  {"Line", "n.", "1. A completed row of blocks on a matrix\n2. The currency of the Hard Drop Café"},
  {"Matrix", "n.", "The playfield onto which the tetrominos fall"},
  {"Mino", "n.", "A small square shape that makes up the\nlarger tetromino"},
  {"Next Queue", "n.", "The area that displays a preview\nof upcoming tetrominos"},
  {"Perfect Clear", "n., v.", "A clear that leaves no blocks on the matrix"},
  {"Single", "n.", "A one-line clear"},
  {"Soft Drop", "n., v.", "The action of dropping a tetromino\nmuch faster than its normal fall rate"},
  {"T-Spin", "n., v.", "The action of rotating or \"spinning\" a\nT tetromino into a spot that covers\nthree of its corners"},
  {"Tetra", "n.", "A four-line clear"},
  {"Tetromino", "n.", "A puzzle piece made with four smaller minos"},
  {"Triple", "n.", "A three-line clear"},
  {"Well", "n.", "A vertical gap one cell wide, typically\nleft as a setup for a Tetra"},
}
